### ISSUE TITLE
Hot keys for commands.

### ISSUE THREAD

**Issue by merosoko** [michaelzangl/minebot#103]
Hello again :) how to assign a key command?
On the server, where I play admin check's logs and ban me every time.Because they read logs, and find there command with /minebot ...
How can I bypass the chat and send commands directly?
I think i can do it if I bind the commands on different keys.But I dont know hot to bind commands :(
Did you know how to do it.Or chet bypass different method?
Sorry for my bad english.I began to teach him recently, before studying German :)
please help me:)

**Comment by michaelzangl** [comment]
The /minebot commands are client only and not present in server logs.

There are however ways to detect if minebot is installed on the client. I do not want to close them because I think that it is the right of the server owner to prevent people from using some mods that might be used to char on his server.
