### ISSUE TITLE
Will this be updated?

### ISSUE THREAD

**Issue by ServerConfigs** [michaelzangl/minebot#276]
Will this be ever updated to 1.13.X? Or does anyone have a fork for it?

**Comment by FzDay7** [comment]
I do really hope that this will be Updated further.. but it looks like its pretty timeconsuming work for the dev to update it.

**Comment by xpr0legendx** [comment]
I have continued development ever since michaelzangl stopped working on this project actively, so for roughly two years. Added lots of new features, improved existing ones and fixed some broken ones. Am hesitant to release it to the public, because much time and effort was put in. 

However, you can update it to 1.13 yourself too. It will show lots of errors in the beginning, but most are duplicates. Fix the errors and start testing if your functions work like they are supposed to, and make changes from there.
