### ISSUE TITLE
Suggestion: Use of enchanted items for different blocks

### ISSUE THREAD

**Issue by ferdal1** [michaelzangl/minebot#31]
How about making the bot select different types of tools according to the block it mines? Not sure if this is possible but an example could be: Do /minebot mine diamond_ore, the bot will mine with a standard diamond pickaxe to the diamond ore, and once it gets to the diamond ore, it changes to a enchanted diamond pickaxe (with fortune and unbreaking enchants), and when finished it changes back to the normal pickaxe and goes to the next ore. Another example could be mining obsidian, in which it could change to a efficiency enchanted pickaxe. Ps: Love your bot :)

**Comment by michaelzangl** [comment]
Fixed in 1340d9fd5b063abb45bbfb9cbeec443a881d2683. There is a wiki page describing it:
https://github.com/michaelzangl/minebot/wiki/Tools

You cannot distinguish between diamond and iron, currently it only takes the enchantments into account.

The default setting is about what you expected.

This will be available in the next release.
