### ISSUE TITLE
Minebot disabling minimap

### ISSUE THREAD

**Issue by yesterdayeightyseven** [michaelzangl/minebot#51]
I was using xaeros_minimap_v1.7.8_Forge_1.8 before I installed Minebot. when I did the mini was gone. it is running cause I still use the in world waypoints...

running minebot .43 in minecraft 1.8....

**Comment by iAmRinzler** [comment]
For some reason minimap mods aren't working with Minebot. BetterPvP mod also will crash minecraft if they are loaded together. I don't know if this is caused by the minimap or something else. 

The quick fix is to disable the incompatible mod when using minebot. Minebot is still compatible with many other mods though.

**Comment by michaelzangl** [comment]
If you need a map and don't runn minecraft full screen, you can use /minebot map start <worldname>. It is not as good as most minimaps but intended to interact with the bot.

**Comment by michaelzangl** [comment]
BetterPVP seems not to be open source. I cannot figure out what is crashing it. Please report to the author of that mod, only he can.

**Comment by eileen12** [comment]
JourneyMap v5.1.3 for Minecraft 1.8 also has problems in displaying the minimap. The full screen map of JourneyMap and all its other features work great however the minimap is invisible. It also has a larger version of the minimap which comes as a bigger square in front but even that is invisible. All this happens only with Minebot.
